import{a as u,i as m,S as h}from"./assets/vendor-43ae9e23.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();u.defaults.headers.common["x-api-key"]="live_387Mr5NSdTViGuSkWsWNpNhx7HXBFt6TTwyYgidC1P2hjqMqtkVYhdbmUqjWvBhp";async function y(){return await u.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}async function g(e){return await u.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(r=>r.data[0])}const p=document.querySelector(".breed-select"),l=document.querySelector(".cat-info"),c=document.querySelector(".loader"),d=document.querySelector(".error");function f(e){m.show({title:"Error",message:`❌ ${e}`,position:"topCenter",color:"red"}),d.textContent=e,d.classList.remove("hidden")}function i(e,r){e.classList.toggle("hidden",!r)}async function b(e){e&&(i(l,!1),i(c,!0),i(d,!1),g(e).then(S).catch(f).finally(()=>{i(c,!1)}))}function S(e){if(e.breeds&&e.breeds.length>0){const{name:r,description:o,temperament:s}=e.breeds[0],t=e.url;l.innerHTML=`
        <img class="cat-img" src="${t}" alt="${r}"/>
        <div class="cat-info-text">
          <h2>${r}</h2>
          <p>${o}</p>
          <p><b>Temperament:</b> ${s}</p>
        </div>
      `,i(l,!0)}else f("No breed information found.")}function v(e){i(p,!0),new h({select:p,settings:{placeholderText:"Search breed"},data:[{placeholder:!0,text:"Select breed"},...e],events:{afterChange:r=>{var o;return b((o=r[0])==null?void 0:o.value)}}})}async function L(){i(c,!0);try{const e=await y();v(e.map(({id:r,name:o})=>({text:o,value:r})))}catch(e){f(e.message)}finally{i(c,!1)}}document.addEventListener("DOMContentLoaded",L);
//# sourceMappingURL=commonHelpers.js.map
